services:

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile

    container_name: house-price-nginx

    ports:
      - "80:80"

    networks:
      - house-price-network


networks:
  house-price-network:
    external: true
    name: house-price-network
